# -*- coding: utf-8 -*-
"""The School Librarian.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hGrXd2g6LaHiWs-HI4ou2LCrFIctjtUV
"""

# load dataset
import pandas as pd
url = "https://docs.google.com/spreadsheets/d/1sfsZhhP2umXXtmEP_NRErxLuwgN98TyH7LWOq3j07O0/export?format=csv&gid=971821388"
df = pd.read_csv(url)
print(df.head())

# keep relevant columns
df = df[['Excerpt', 'BT Easiness', 'Flesch-Kincaid-Grade-Level']]
df = df.dropna()
print(df.head())

# get BERT embeddings
from transformers import BertTokenizer, BertModel
import torch

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

def get_embedding(text):
  inputs = tokenizer(text, return_tensors = "pt", truncation = True,
                     padding = True, max_length = 512)
  with torch.no_grad():
    outputs = model(**inputs)
  return outputs.last_hidden_state.mean(dim = 1).squeeze().cpu().numpy()

# feature matrix
import numpy as np

embeddings = []
for text in df['Excerpt']:
  emb = get_embedding(text)
  embeddings.append(emb)

X = np.array(embeddings)
y = df['BT Easiness'].values

# ml training split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

# linear regression baseline
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

# evaluate model
from sklearn.metrics import mean_squared_error, r2_score

y_pred = model.predict(X_test)

print("MSE:", mean_squared_error(y_test, y_pred))
print("R2:", r2_score(y_test, y_pred))

# compare against baseline
fkg_scores = df.loc[y_test.index, 'Flesch-Kincaid-Grade-Level']

print("FKG vs. True:", mean_squared_error(fkg_scores, y_test))
print("BERT vs. True:", mean_squared_error(y_pred, y_test))